### PR TITLE
Math magicians: Quotes

### PR DESCRIPTION
**Pull request by lily4178993**
# Math magicians: Quotes
In this branch, I fetch data from an external API -- [API Ninjas](https://api-ninjas.com/) -- to display "quotes" alongside the calculator.

## Changes implemented:

- Create a new component -- _Quotes_ -- for displaying a quote
- Fetch data inside of a new component
- Show a `loading` state
- Show an `error` state
- Import the  -- _Quotes_ -- component into the main component (next to the Calculator)

## How should this app be tested?
Clone this repository:
```sh
git clone https://github.com/lily4178993/Math-Magicians.git
```

Checkout the branch:
```sh
cd Math-Magicians
git checkout calc-quotes
```

Install all dependencies:
```sh
npm install
```

Open the project:
```sh
npm start
```

Please kindly review my implementation and suggest any changes and improvements.  Best regards.
Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by AlphaNtihinduka — COMMENTED** [review]
Hi @lily4178993 ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
# Invalid Code Review Request ❌ 
was-that-wrong-icegif

- [ ] It has been communicated that the Errors with `webhint` have been fixed. Kindly ensure to add the webhint error checkers ☺️.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by lily4178993** [comment]
Hi @AlphaNtihinduka. This is a React project. When setting up the linters, I do not need to add webhint here.
You can see the refered pull request [here](https://github.com/lily4178993/Math-Magicians/pull/2).
[Here](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_setup.md), you will see the linters required for this project.

If I have misunderstood your point of view, please explain it.

**Comment by AlphaNtihinduka** [comment]
Hello @lily4178993 I apologize for the inconviences, You may consider requesting for a review again. The previous review comment will be ignored. Thank you for the feedback.

**Comment by lily4178993** [comment]
No problem. Have a nice day @AlphaNtihinduka.

**Review by AdnanOlarmmi — APPROVED** [review]
Hi @lily4178993,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Approved office man

## Highlights
- UseEffect hooked used effectively.
- App is working.
- API Fetch call made effectively.
- Clear and well-organized code.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Hi @AdnanOlarmmi. Thank you for taking the time to review my pull request.
Have a nice day.

**Pull request merged**
