### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by lily4178993**
# Math Magicians: Project setup
This branch is raised in order to set up all linters necessary for the Math Magicians project.

## Changes implemented so far:
- Create a Math Magician application is using [Create React App](https://create-react-app.dev/)
- Set-up GitHub Actions by creating linters.yml
- Set-up ESLint
- Set-up Stylelint

## How should this app be tested?
Clone this repository:
```sh
git clone https://github.com/lily4178993/Math-Magicians.git
git checkout project-setup
cd Math-Magicians
```

Install all dependencies:
```sh
npm install
```

Open the project:
```sh
npm start
```

Please kindly review my implementation and suggest any changes and improvements.  Best regards.
Thanks for reviewing my PR 😊

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi @lily4178993, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not a professional README file. Kindly use this recommended Microverse [README template](https://github.com/microverseinc/readme-template) and resubmit the project for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by lily4178993** [comment]
Thank you @LionRouge1 for taking the time to review my PR

**Comment by NahnahAJ** [comment]
## Project Status: INVALIDATED :red_circle: 
Hi @lily4178993 , 

While you made a great effort in this project, I can't go ahead and review your code.


## Invalid Code Review Request

- [ ]  I noticed that you removed some of the `headers/sections` from the [Microverse Readme Template](https://github.com/microverseinc/readme-template). This makes your project incomplete as every section of the readme template is required except for the `FAQ section` which is optional. So please make sure to add all the missing `headers/sections` in the README template to your project and fill in all the necessary contents :+1:
- [ ]  Please ensure that The README also contains the original complete list of `Table of Contents` and ensure that when a topic is clicked on in the table of contents, it takes you to its related section :wink:

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mckent05 — APPROVED** [review]
Hi @lily4178993, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
approved


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Good job setting up your react project using CRA 👍 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you all for taking the time to review my PR

**Pull request merged**
